### ISSUE TITLE
"TypeError: path.charAt is not a function"

### ISSUE THREAD

**Issue by cesarandreu** [feross/eslint-config-standard-react#1]
Since https://github.com/eslint/eslint/pull/2711 isn't in a tagged release yet, if your _.eslintrc_ file has:

``` json
{
  "extends": ["standard", "standard-react"]
}
```

It'll throw `TypeError: path.charAt is not a function`.

It looks like standard is using a hardcoded eslint: https://github.com/feross/standard/blob/22e640da289a6d30e631bacbd85037ba33d776de/package.json

For people that wanna use this on its own, you'll need to install the hard-coded version of eslint until there's a new tagged release.

Maybe it's a good idea to add a temporary note to the README?

**Comment by cesarandreu** [comment]
For anyone that might have this same issue, in the meantime it can be solved by using:

``` json
{
  "eslint": "git://github.com/eslint/eslint.git#fff52aecaf1d073952201b3f128e6664f529a24e"
}
```

**Comment by feross** [comment]
@cesarandreu Yeah, feel free to add a note to the readme! Good idea!

**Comment by feross** [comment]
eslint 0.23.0 is now released so this is no longer an issue! :+1:

**Comment by cesarandreu** [comment]
:+1:

**Comment by 0x80** [comment]
I'm getting the same error in Sublime and I am at eslint 0.24 already. 

This is my project npm list:

eslint.........................[0.24.1]
eslint-config-standard..........[3.4.1]
eslint-config-standard-react....[1.0.1]
eslint-plugin-react.............[2.7.1]

Any idea what might be causing this?
