### ISSUE TITLE
props validation for stateless components

### ISSUE THREAD

**Issue by jasonblanchard** [feross/eslint-config-standard-react#10]
For a sateless component that looks like this:

``` jsx
const statelessComponent = (props) => {
  const subRender = () => {
    return <span>{props.someProp}</span>;
  };

  return <div>{subRender()}</div>;
};

statelessComponent.propTypes = {
  someProp: PropTypes.string
};
```

eslint throws:

```
'someProp' is missing in props validation
```

Which is odd, because `someProp` is definitely in `propTypes`. A work-around to satisfy the linter is to store the prop in a variable outside `subRender` the function:

``` jsx
const statelessComponent = (props) => {
  const someProp = props.someProp;

  const subRender = () => {
    return <span>{someProp}</span>;
  };

  return <div>{subRender()}</div>;
};

statelessComponent.propTypes = {
  someProp: PropTypes.string
};
```

I think this is either a bug in how the linter is checking for prop types, or, if the latter example is a preferred style, the message should be clearer about what's wrong here.

**Comment by natorojr** [comment]
:+1:

**Comment by jasonblanchard** [comment]
Oops, wrong project. Closing and moving over here https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md
