### ISSUE TITLE
Indent error: expected indentation of 2 space characters but found 4

### ISSUE THREAD

**Issue by alayek** [feross/eslint-config-standard-react#14]
Hi, I am using this linter standard within a project, and I got this error with this code here:

https://github.com/alayek/Markpad/blob/devel/src/components/AppNavBar.js#L6

In this line, it says 

> error  Expected indentation of 2 space characters but found 4

Is this an issue with the linter, or are we doing something wrong? I would normally ask in some forum or chat channel; but I couldn't find anything like that.

Thanks in advance.

**Comment by dcousens** [comment]
It looks OK,   but there has been issues around class properties [of late](https://github.com/feross/standard/issues/372).

**Comment by feross** [comment]
This is probably fixed in standard v6.
