### ISSUE TITLE
Definition for rule 'react/jsx-indent' was not found

### ISSUE THREAD

**Issue by P3at** [feross/eslint-config-standard-react#16]
I'm getting a project linting error "Definition for rule 'react/jsx-indent' was not found" using version 2.0.0. Using 1.2.1  doesn't give me any issue.

Also seeing "Parsing error: Unexpected token <" in any file containing tags. Again, only with 2.0.0.

**Comment by dignifiedquire** [comment]
Are you using the latest versions of `eslint-plugin-react` and `eslint`?

**Comment by P3at** [comment]
```
    "eslint": "^2.0.0-rc.0",
    "eslint-plugin-react": "^3.16.1",
```

My eslint didn't update to a 2.0.0 release, didn't notice. Now I get "Parsing error: 'import' and 'export' may appear only with 'sourceType: module' which may not be related to this, sorry if it isn't

**Comment by P3at** [comment]
I'm actually getting a slew of errors the more I dig into this. 

The setup i'm using is
Atom:
- language-babel package
- linter package
- linter-eslint package

package.json snippet:

```
"eslint": "^2.0.0-rc.0",
"eslint-config-standard": "^4.4.0",
"eslint-config-standard-react": "^2.0.0",
"eslint-plugin-react": "^3.16.1",
"eslint-plugin-standard": "^1.3.1",
```

.eslintrc:

```
{
  "extends": ["standard", "standard-react"]
}
```

Looking at the migration guide for eslint 2.0.0, adding

```
parserOptions: {
  sourceType: "module"
}
```

Fixed the above error I was getting, but then I get one like "Rule 'no-empty-label' was removed and replaced by: no-labels". Maybe i'm just getting ahead of myself and should keep everything at the version I've been using until more time has passed.

**Comment by feross** [comment]
Yeah, sorry about this. This is because I haven't published an analogous version of `eslint-config-standard` that's meant to be used with this yet. The current version of `eslint-config-standard` still assumes eslint 1.x. I wouldn't upgrade just yet. :)

**Comment by P3at** [comment]
Gotcha, thanks for the help!
