### ISSUE TITLE
allow ignoreRef for 'jsx-no-bind'

### ISSUE THREAD

**Issue by sorahn** [feross/eslint-config-standard-react#20]
Facebook says they're deprecating ref's as strings, so I was thinking that this rule should be loosened a bit to allow binds for refs.

For ref's you usually want to just quickly assign it to the class, and if you need multiple ref's in a file its a little weird to just have a bunch of ref adding functions.

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

`<Component ref={c => this.component = c} />`

Thoughts?

**Comment by feross** [comment]
@cesarandreu @dcousens React users -- thoughts?

**Comment by dcousens** [comment]
I never use refs, so I don't have enough experience to really help with this.

**Comment by dignifiedquire** [comment]
Doesn't this bring the same perf issues as other bindings? If so I'm against loosening it by default as it defeats the purpose of the rule. You can always override it in your project if you don't want to adhere to the rule.

**Comment by sorahn** [comment]
@dignifiedquire Are there performance issues with using the fat arrows in functions like that? I Thought those issues were all with using .bind

**Comment by dignifiedquire** [comment]
@sorahn Yes there are, that's the reason why this rule checks for them as well, these function get recreated on each render, the same way if you would do bind. Simple example:

``` js
function render () {
  // This will create a new function on every call
  return `hello ${() => 'world'}`
}

function render2 () {
  // bind will create a new function on every call
  return `hello ${worldMaker.bind(null, 'world')}`
}

function render3 () {
  // all good, just a function call, no creation of a function
  return `hello ${worldMaker()}`
}
```

**Comment by sorahn** [comment]
Ah, ok thanks for the clarification :)

We ended up just making something like this so we don't have to override the rule :)

``` javascript
const makeRef = (name) => (component) => {
  this[name] = component
}


<Foo ref={this.makeRef('Foo')} />
```

**Comment by louh** [comment]
Hey - I'd like to reconsider this issue.

I can't say much for the performance aspects, but the _official React documentation_ recommends arrow functions to assign refs (https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute).

If we're unable to do this within `standard`, the options are to continue to use string refs against React's recommendation, or do something like the way @sorahn has done, but this is not a well known strategy. Furthermore, it would be unwieldy to declare this function in every component that needs refs. I would mind less if this was already a common community convention, but it is not. Contrast this with the use of `.bind(this)` within props, which already has a common convention to bind in the constructor instead ([for example](https://github.com/airbnb/javascript/tree/master/react#methods)).

I would like to propose a recommendation to relax this rule for callback refs.

Thanks!

**Comment by feross** [comment]
@louh Can't the same `.bind(this)` approach be used in the constructor for refs too?

``` js
class Foo extends React.Component {
  constructor () {
    super()
    this._onRef = this._onRef.bind(this)
  }
  render () {
    return (
      <div ref={this._onRef}>
        Hello!
      </div>
    );
  }
  _onRef (component) {
    // Do whatever you like, referencing "this" as appropriate
  }
}
```

**Comment by louh** [comment]
I do like this version better as it's more readable, but it's still not "common" usage (e.g. it would need to be the recommended, documented way of setting `ref`s or have enough widespread adoption that this is naturally the right thing to do). Furthermore it seems that using `.bind(this)` at all just gets around the rule, but re-introduces the kind of performance hit that @dignifiedquire was so concerned about. [These threads](https://github.com/airbnb/javascript/issues/801) at the Airbnb styleguide seems to indicate that even using `.bind(this)` in the constructor once is slower than recreating arrow functions at render time.

In practice, I've seen no observable performance hit at all in using arrow functions to create refs, and while I don't doubt that it might be slower in heavy computations, when I've seen slow renders it is usually in code that cause significant re-renders in a short amount of time, e.g.  not throttling events like "scroll" or "resize" that might cause re-renders, or using `this.setState()` more than once in asynchronous functions (which are not batched by React), or by having very large stateful components in general, none of which are linted by Standard. Furthermore, the solutions proposed here still feels like workarounds with extra boilerplate code that hasn't been documented anywhere outside of this thread (that I know of).

So far it's the first rule in Standard I've had to override for feeling unnecessarily strict with no perceived benefit.

**Comment by feross** [comment]
@louh Sure. I don't have strong opinions on this, so I'm happy to go along with the airbnb guide here and be a bit more permissive about what we allow.

**Comment by feross** [comment]
4.0.1

**Comment by louh** [comment]
Thanks :-)
