### ISSUE TITLE
Reintroduce react-in-jsx-scope rule

### ISSUE THREAD

**Issue by laurentdesmet** [feross/eslint-config-standard-react#24]
As per commit 263162f, `react-in-jsx-scope` was removed from this config. If I understand the history of this project well, then at some point eslint-config-standard-jsx was created (after commit 263162f was applied) that contains rules that apply to JSX in general, and not specifically React.

If the aim of this project is to protect against specific React errors, then this rule should be reintroduced because a React component will fail at runtime, when `React` is not in scope when using JSX.

**Comment by dcousens** [comment]
@laurentdesmet  could you give an example?

**Comment by laurentdesmet** [comment]
This will fail at runtime with an _Uncaught ReferenceError: React is not defined_

``` javascript
import ReactDOM from 'react-dom'
// import React from 'react'

const Component = () => <div>Hello World!</div>

ReactDOM.render(
  <Component />,
  document.getElementById('app')
)
```

Removing the comment at line 2 will make it succeed. We can prevent this mistake by adding the `react-in-jsx-scope` rule.

**Comment by dcousens** [comment]
:+1: LGTM, make a PR
