### ISSUE TITLE
Consider new rules from eslint-plugin-react@3

### ISSUE THREAD

**Issue by feross** [feross/eslint-config-standard-react#3]
eslint-plugin-react v3 was released. I wanted to make sure you react folks (@dcousens, @cesarandreu, @jprichardson, @dcposch) knew about it.

If there are any rule changes you want to make, please go ahead. standard v5 will be upgrading the eslint-plugin-react dependency from v2 to v3.

This is their changelog:
#3.1.0 / 2015-07-28
- update dependencies
- add event handlers to no-unknown-property ([#164](https://github.com/yannickcr/eslint-plugin-react/pull/164) @mkenyon)
- add customValidators option to prop-types ([#145](https://github.com/yannickcr/eslint-plugin-react/issues/145) @CalebMorris)
- fix comment handling in jsx-curly-spacing ([#165](https://github.com/yannickcr/eslint-plugin-react/issues/165))
- documentation improvements ([#167](https://github.com/yannickcr/eslint-plugin-react/pull/167) @ngbrown)
#3.0.0 / 2015-07-21
- add jsx-no-duplicate-props rule ([#161](https://github.com/yannickcr/eslint-plugin-react/pull/161) @hummlas)
- add allowMultiline option to the jsx-curly-spacing rule ([#156](https://github.com/yannickcr/eslint-plugin-react/pull/156) @mathieumg)
- breaking in jsx-curly-spacing braces spanning multiple lines are now allowed with never option ([#156](https://github.com/yannickcr/eslint-plugin-react/pull/156) @mathieumg)
- fix multiple var and destructuring handling in props-types ([#159](https://github.com/yannickcr/eslint-plugin-react/issues/159))
- fix crash when retrieving propType name ([#163](https://github.com/yannickcr/eslint-plugin-react/issues/163))

**Comment by dcousens** [comment]
`no-unknown-property` looks good,  provided it only occurs for DOM elements (library authors may not be so consistent).

`jsx-no-duplicate-props` LGTM.

**Comment by michaelabon** [comment]
@dcousens Author of the upgrade to `no-unknown-property` here. I'm not a fan of the name, but it does only occur on DOM elements, not React components. It reminds you that JSX prefers `onClick` to `onclick` and `acceptCharset` to `accept-charset`. There [are specs](https://github.com/mkenyon/eslint-plugin-react/blob/8704c65dc63097b4f1c4b7609e28a25afc3c9178/tests/lib/rules/no-unknown-property.js) to help verify that.

**Comment by feross** [comment]
Please test it on some of your code. If you think it looks good, please send a PR and (if you're feeling bold) publish a new version to npm!

**Comment by feross** [comment]
Closing this stale issue.
