### ISSUE TITLE
modify rule jsx-no-bind

### ISSUE THREAD

**Issue by rgranger** [feross/eslint-config-standard-react#34]
commit : d2352bdac46c97375145e1b4d84eaff725f960d7
I saw in this commit that you modified this rule :

<pre>
"react/jsx-no-bind": 2
</pre>

for this : 

<pre>
 "react/jsx-no-bind": [2, {
     "allowArrowFunctions": true,
     "allowBind": false,
     "ignoreRefs": true
 }]
</pre>

Is this intentional or is it just a mistake ?

As far as i know, using arrow functions in render is still an anti-pattern :
https://medium.com/@esamatti/react-js-pure-render-performance-anti-pattern-fb88c101332f#.hz1kmeu4g
https://medium.com/@machnicki/handle-events-in-react-with-arrow-functions-ede88184bbb#.oo0nompik

Thus, in my opinion, the rule should be :

<pre>
 "react/jsx-no-bind": [2, {
     "allowArrowFunctions": false,
     "allowBind": false,
     "ignoreRefs": false
 }]
</pre>

which is equivalent to

<pre>
"react/jsx-no-bind": 2
</pre>

**Comment by feross** [comment]
Arrow functions aren't a big performance hit. See https://github.com/airbnb/javascript/issues/801 for more discussion.

**Comment by rgranger** [comment]
Ok, that makes sense.
So, from what I understood :

* .bind is slow, whereas () => {} is not
*  when using a stateful component, bind handlers in the constructor, but prefer using a stateless component with arrow functions for handlers in render

**Comment by feross** [comment]
Yes, that's correct.

**Comment by frederikhors** [comment]
@feross is this still a thing today?

Are we sure arrow functions in render are ok?

**Comment by feross** [comment]
@frederikhors I believe that arrow functions are still fine to be used in `render()`.
