### ISSUE TITLE
Using stateless function through function invoking way hints me missing props validation.

### ISSUE THREAD

**Issue by zheeeng** [feross/eslint-config-standard-react#39]
When using stateless function through function invoking, React doesn't validate the props' type, but rule react/prop-types hints you write component's propTypes. It doesn't make sense. 
```
const renderHello = ({ name }) => (
    <h1>Hello {name}</h1>
)

// It doesn't work at all, so you can define the prop name to any types. If you missed it eslint will hint you missing props validator.
renderHello.propTypes = {
  name: PropTypes.func
}

const App = () => (
  <div>{renderHello({ name: 'world' })}</div>
)

```

This way, its imperative to write propTypes.
```
const Hello = ({ name }) => (
    <h1>Hello {name}</h1>
)

Hello.propTypes = {
  name: PropTypes.string
}

const App = () => (
  <div><Hello name={'world'} /></div>
)
```

**Comment by feross** [comment]
It's not clear to me if the react eslint plugin supports what you're asking for. If it does, please send a PR changing the rule and I'll be happy to review it.
