### ISSUE TITLE
Question: why is react/wrap-multilines = 2?

### ISSUE THREAD

**Issue by rstacruz** [feross/eslint-config-standard-react#4]
This is considered ok:

``` js
let Hello = React.createClass({
  render () {
    return (
      <div>
        <p>Hello {this.props.name}</p>
      </div>
    )
  }
})
```

But this isn't:

``` js
let Hello = React.createClass({
  render () {
    return <div>
      <p>Hello {this.props.name}</p>
    </div>
  }
})
```

Just wondering, what's the rationale behind this decision?

**Comment by feross** [comment]
I have no opinion on this. If you send a PR that removes the relevant rule I will merge it, unless the other collaborators have a differing opinion.

**Comment by feross** [comment]
This was fixed in #5.

**Comment by bigomega** [comment]
@rstacruz 
Having said that this rule can be disabled.

It's more readable when written like the first case. You end the tag where you start it, just like html.

**Comment by agrcrobles** [comment]
it is deprecated now
