### ISSUE TITLE
error using Class Properties with React

### ISSUE THREAD

**Issue by loconluis** [feross/eslint-config-standard-react#46]
```
state = {
    collapse: false
}
```

The error occurs, when I put the state like show above using class properties, says that the equal sign (=) is an unexpected token. 🙁

<img width="282" alt="captura de pantalla 2018-03-17 a la s 15 42 45" src="https://user-images.githubusercontent.com/12422912/37560207-dfc0b880-29f9-11e8-90b8-c96473d3560e.png">

**Comment by feross** [comment]
You need to install `babel-eslint` and set it as your parser. See: https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features
