### ISSUE TITLE
Shouldn't this lib follow the React rules in Standard?

### ISSUE THREAD

**Issue by lourenci** [feross/eslint-config-standard-react#54]
I say that because `"react/jsx-no-bind"`, `"react/no-did-update-set-state"` and `"react/prop-types"` all are `off` in Standard.

**Comment by feross** [comment]
This package used to be included directly in `standard` but it was restricting too many use cases where people use JSX with non-React frameworks, so we removed it and just kept the barebones JSX rules that are not React-specific in `standard`.

So, at the moment, this repo is just for extra rules that folks think are a good idea. If you have recommendations for how to change it, please send PRs. I'm relatively un-opinionated about this package and happy to get feedback and suggestions from the community.
