### ISSUE TITLE
missing in props validation

### ISSUE THREAD

**Issue by reggi** [feross/eslint-config-standard-react#6]
I'm using the `standard` command and the atom linter and for the code below it's stating `'url' is missing in props validation`. Do I have to switch to eslint and config files? I'd really like to be able to use `standard` and the atom linter.

```jsx
var Layout = require('./layout.jsx')
var React = require('react')

module.exports = React.createClass({
  render: function render () {
    return (
    <Layout {...this.props}>
      <h3>URL: {this.props.url} - Not Found(404)</h3>
      <h6>I am a Plain vanilla react view</h6>
    </Layout>
    )
  }
})
```

**Comment by despairblue** [comment]
How about just adding the props validation?

``` javascript
var Layout = require('./layout.jsx')
var React = require('react')

module.exports = React.createClass({
  propTypes: {
    url: React.PropTypes.string.isRequired
  },

  render: function render () {
    return (
    <Layout {...this.props}>
      <h3>URL: {this.props.url} - Not Found(404)</h3>
      <h6>I am a Plain vanilla react view</h6>
    </Layout>
    )
  }
})
```

**Comment by feross** [comment]
I'm cool with removing this rule. I don't have particularly strong opinions about React. If @dcousens or @cesarandreu have an opinion, let's defer to them.

**Comment by dcousens** [comment]
@feross this rule is very useful,  especially at catching spelling mistakes etc.

It is also highly encouraged by the React team.
It can easily be added as an inlined disabled rule, but that definitely shouldn't be the norm.

**Comment by feross** [comment]
Okay - let's close this then.

**Comment by despairblue** [comment]
Just chiming in one last time: Are you aware that this rule does not work with static class properties?

``` javascript
// does not work because standard cannot parse it
export default class Foo extends Component {
  static propTypes = {
    style: PropTypes.object.isRequired
  }
  render () {
    return <View style={this.props.style}/>
  }
```

This would only work with babel-eslint as of now, see https://github.com/yannickcr/eslint-plugin-react/issues/43

**Comment by feross** [comment]
@dcousens thoughts?

**Comment by cesarandreu** [comment]
@despairblue static class properties require you use babel with stage 0, I don't think it's unreasonable that you'd need to configure babel-eslint as the parser.

If you're only using ES6 classes the correct way to define propTypes is shown in the [react docs](http://facebook.github.io/react/docs/reusable-components.html):

``` jsx
export class Counter extends React.Component {
  constructor(props) {
    super(props);
    this.state = {count: props.initialCount};
  }
  tick() {
    this.setState({count: this.state.count + 1});
  }
  render() {
    return (
      <div onClick={this.tick.bind(this)}>
        Clicks: {this.state.count}
      </div>
    );
  }
}
Counter.propTypes = { initialCount: React.PropTypes.number };
Counter.defaultProps = { initialCount: 0 }
```

Having the rule enabled is very useful, I'm against disabling it.

**Comment by reggi** [comment]
Thanks @despairblue didn't know declaring the `propType` would take care of it, works great!

**Comment by despairblue** [comment]
@cesarandreu thank you, I only read the _Prop Validation_-part of the docs and the only thing I found was: https://babeljs.io/blog/2015/06/07/react-on-es6-plus/ which does not show the intermediate solution. :+1:

**Comment by dlmanning** [comment]
@despairblue : Is it possible to add an exception for `this.props.children`? Do you feel like there's value in declaring a type there?

**Comment by dcousens** [comment]
@dlmanning I've had that come up several times,  and I'm still not sure about an answer.
In the one case,  it could give warning to the user if `children` isn't what they expected.
In the other,  its blatant boiler plate that is almost _always_ going to be `React.PropTypes.node` (IIRC).

**Comment by reggi** [comment]
I agree @dcousens @dlmanning `children` doesn't need to be validated, I've been including this in all my components, it would be nice if it wasn't required.

``` jsx
propTypes: {
  children: React.PropTypes.node
}
```

**Comment by dcousens** [comment]
I think the above would only make sense if `React` automatically specified a propType for `children` by default.
If we omit it,  the user will not have type validation for `children`.

**Comment by dlmanning** [comment]
@dcousens : The user can still specify propType validation for children if they actually want it. This feels like overkill for standard.

**Comment by dcousens** [comment]
@dlmanning I understand the sentiment.  The reality is that right now its all or nothing,  so unless we have a way to differentiate,  I'm still in favour of always requiring prop types.

**Comment by dlmanning** [comment]
@dcousens : I have no desire to be contentious about this: it's a small thing either way. However, there's an option that can be passed for this rule set to disable linting for particular property names should you decide to go that way:

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md#rule-options

**Comment by dcousens** [comment]
@dlmanning perhaps we should open a separate issue [in this repo],  weigh out the pros and cons and decide there?
I think in general this rule is worth having,  its just these edge cases that may or may not be worth it.

ping @jprichardson

**Comment by skantus** [comment]
```javascript
ClassName.propTypes = {
   navigation: PropTypes.shape({
    navigate: PropTypes.func.isRequired
  }).isRequired
};
```

**Comment by gurol** [comment]
https://stackoverflow.com/a/49686927/2101864 provides up-to-date information.

**Comment by tguzi** [comment]
when i remove extends 'plugin:react/recommended', i solved the problem. maybe you can try it too
