### ISSUE TITLE
Error - .eslintrc.js » eslint-config-standard-react

### ISSUE THREAD

**Issue by vedmant** [feross/eslint-config-standard-react#64]
**What version of this package are you using?**
"eslint": "^6.6.0",
"eslint-config-standard-react": "^9.2.0",

**What operating system, Node.js, and npm version?**
node: v12.8.0
yarn: 1.17.3 

**What happened?**

[Error - 6:03:17 PM] .eslintrc.js » eslint-config-standard-react » /Users/vedmant/Projects/_My/MY-10 RunningTimeApp/RunningTimeRN/node_modules/eslint-config-standard-jsx/index.js: 	Configuration for rule "react/jsx-indent" is invalid: 	Value {"checkAttributes":true,"indentLogicalExpressions":true} should NOT have additional properties. 

**What did you expect to happen?**

No error

**Are you willing to submit a pull request to fix this bug?**

No

**Comment by alexei-sevrukov-topx** [comment]
the same error when install for react-native 0.61.5, react 16.9.0

**Comment by sidntrivedi** [comment]
@feross How to fix this error? Thanks.

**Comment by feross** [comment]
Update your `eslint` and `eslint-plugin-react` dependencies the latest version and this error will go away.
