### ISSUE TITLE
Adding React Hooks rules

### ISSUE THREAD

**Issue by liegeandlief** [feross/eslint-config-standard-react#65]
Hey there, is it still the plan to add the React Hooks rules to Standard as discussed in https://github.com/standard/eslint-config-standard-react/pull/63? This would be super useful. Thanks :)

**Comment by feross** [comment]
Yes, still planned in a future version of `standard`.

**Comment by feross** [comment]
Duplicate of https://github.com/standard/eslint-config-standard-react/issues/57
