### ISSUE TITLE
Release the ESLint 8 version

### ISSUE THREAD

**Issue by voxpelli** [feross/eslint-config-standard-react#73]
It's been requested in: https://github.com/standard/eslint-config-standard-react/pull/69

See also: https://github.com/standard/eslint-config-standard/issues/229

**Comment by flippidippi** [comment]
Any updates on this?

**Comment by framerate** [comment]
Please!

**Comment by fnwbr** [comment]
At medienhaus/ we've started using the workaround to specify a git commit hash as the version for the npm package. Since the issue was basically fixed on the `master` branch and we're all just waiting for the release on npm for it, this will solve the problem (and potential issues with `npm install`) in the meantime:
https://github.com/medienhaus/medienhaus-cms/commit/9f00f9c56e0607d4c6c96780f17b2226f6279f44

**Comment by derekhubbard** [comment]
Any update on this? Until this is fixed, I don't see a clean path forward to us using the latest version of node and npm due to invalid peer dependency checks.

**Comment by voxpelli** [comment]
I'm a bit choked right now, but I will have some discussions on this subject tomorrow, I may come back after that and see

**Comment by voxpelli** [comment]
Also, you probably want to use [`eslint-config-standard-jsx`](https://github.com/standard/eslint-config-standard-jsx) instead of this one. That's why this wasn't included in the major releases of `standard@17`, because `standard` itself uses `eslint-config-standard-jsx` and it's a bit unclear to me whether this module is actually deprecated by that one or not.

**Comment by voxpelli** [comment]
Note to self:

From the looks of it this is a straight extension on top of the jsx one: https://github.com/standard/eslint-config-standard-react/commit/c357387937a7cfcaad33cbe6e3ac7f4a990d170d

> BREAKING: Stop extending from eslint-config-standard-jsx
> 
> To update, you will need to:
> 
> npm install eslint-config-standard-jsx
> 
> And then ensure that "standard-jsx" appears in the "extends" section of your .eslintrc:
> 
> "extends": [
>     "standard-react", "standard-jsx"
>   ]

**Comment by flippidippi** [comment]
> Note to self:
> 
> From the looks of it this is a straight extension on top of the jsx one: [c357387](https://github.com/standard/eslint-config-standard-react/commit/c357387937a7cfcaad33cbe6e3ac7f4a990d170d)
> 
> > BREAKING: Stop extending from eslint-config-standard-jsx
> > To update, you will need to:
> > npm install eslint-config-standard-jsx
> > And then ensure that "standard-jsx" appears in the "extends" section of your .eslintrc:
> > "extends": [
> > "standard-react", "standard-jsx"
> > ]

I agree. I feel like these rules should be rolled into `eslint-config-standard-jsx`

**Comment by voxpelli** [comment]
@flippidippi The rules in `eslint-config-standard-react` are the React specific ones on top of the basic JSX ones, so they can't be added to `eslint-config-standard-jsx`.

Whether it's meaningful to maintain in addition to `eslint-config-standard-jsx` and possibly creating confusion in how to use them: That can be discussed

**Comment by JounQin** [comment]
When will this be released??

**Comment by mirismaili** [comment]
When will this be released???

**Comment by flippidippi** [comment]
Can we just release this for now until we figure out the `jsx` vs `react` direction? I think it makes sense to consolidate those, but until that's done, I feel like this should just be released as is so people can upgrade to 8.

**Comment by framerate** [comment]
@flippidippi I fear most of us have just moved on to other solutions, this project almost appears abandoned. But hopefully somebody proves me wrong! Big fan

**Comment by mkasprz** [comment]
Without the release I feel forced to pull version directly from Github as otherwise I expeced some conflict with some other package (I'm not sure which one now, but possibly "@babel/eslint-parser"). Would be grateful for it.

**Comment by s100** [comment]
It's been six months, this obviously isn't coming. I suggest just stopping using this package.

**Comment by voxpelli** [comment]
Released as [`12.0.0`](https://github.com/standard/eslint-config-standard-react/releases/tag/v12.0.0), though I don't use this one myself so please report any bugs back

**Comment by mkasprz** [comment]
Great, thank You!
